# Generated by Django 2.1.5 on 2019-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Жаңылыктын Аты')),
                ('body', models.TextField(verbose_name='Жаңылык')),
                ('photo', models.ImageField(blank=True, default='images/def.jpg', upload_to='images/', verbose_name='Сүрөт')),
            ],
        ),
    ]
