# Generated by Django 2.1.5 on 2019-09-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='choice_group',
            field=models.ForeignKey(blank=True, default='100', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='table.Group'),
        ),
    ]
