# Generated by Django 2.2.5 on 2019-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20190912_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='garden_address',
            field=models.CharField(max_length=50, verbose_name='Бала бакчанын дареги'),
        ),
        migrations.AlterField(
            model_name='name',
            name='garden_email',
            field=models.CharField(max_length=20, verbose_name='Бала бакчанын почтасы'),
        ),
        migrations.AlterField(
            model_name='name',
            name='garden_info',
            field=models.TextField(verbose_name='Бала бакча жөнүндө маалымат'),
        ),
        migrations.AlterField(
            model_name='name',
            name='garden_name',
            field=models.CharField(max_length=30, verbose_name='Бала бакчанын аты'),
        ),
        migrations.AlterField(
            model_name='name',
            name='garden_phone',
            field=models.CharField(max_length=20, verbose_name='Бала бакчанын телефону'),
        ),
    ]
