# Generated by Django 2.2.5 on 2019-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20190913_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_img',
            field=models.ImageField(blank=True, default='images/def.jpg', upload_to='images/', verbose_name='Тайпанын cүрөтү'),
        ),
    ]
